# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f56154322609df1073aa1ad1e3f0a8315a5886739bd4016951f8ca9e99f05f8f55e631e0d74f889593929e013ad5c0142b29389968c0a6b32f6404bd1504ed88

test:
  secret_key_base: 91fcd55efb07666259c06b934f5dd8a8bd2c37f243829bd6fe1d1f1bbd9cbdd4bf6aaa81453c331943df0b6f443f69c77e4118796b55443dcf706232a2bcc03e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
